project:
  type: website

website:
  title: "Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
